### ISSUE TITLE
dynamic naming for the product of make system

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-project/nerves-system-br#37]
I would like to be able to control both the name of the resulting archive as well as the name of the decompressed archive folder when running `make system` Bakeware requires this to prevent middle steps of having to unpack and rename everything

**Comment by fhunleth** [comment]
`make system` just calls out to `scripts/mksystem.sh` with no commandline arguments. The first argument to `mksystem.sh` is the archive name (without the `.tar.gz`) and folder. 

Could you just run `scripts/mksystem.sh $YOUR_DESIRED_ARCHIVE_NAME`?

**Comment by mobileoverlord** [comment]
perfect
