### ISSUE TITLE
Make a .deb for fwup to make it easier to install on linux, maybe using fpm [from #nerves TODO list]

### ISSUE THREAD

**Issue by ChuckLutz** [nerves-project/nerves-system-br#55]
(From the #nerves channel TODO list I've been culling):
Date: 01 Mar
Participants: fhunleth, gregmefford, bordeltabernacle
Details:
- Make a .deb for fwup to make it easier to install on linux
  - tedo also suggested an rpm, perhaps made with https://github.com/jordansissel/fpm/wiki/PackageMakeInstall (02 Mar, tedo, chuck_lutz)
  - gregmefford supported the idea to use fpm, adding "Probably wouldn't be acceptable to send upstream, but fine as a self-hosted package."

**Comment by fhunleth** [comment]
Done. The latest version of `fwup` includes .deb and .rpm packages in the releases. See the README at https://github.com/fhunleth/fwup under "Installing".
